"""
03_sentiment_analysis.py

Sentiment Analysis Model.

Uses VADER (Valence Aware Dictionary and sEntiment Reasoner) as the
pretrained sentiment model — a lexicon/rule-based analyzer requiring no
model download, matching the brief's "use a pre-trained model" instruction
without needing huggingface.co access (see README "Environment
Limitations"). This is also consistent with the original dataset generation
notebook, which used VADER to assign these very sentiment labels in the
first place.

IMPORTANT CAVEAT (documented, not hidden): because the dataset's sentiment
labels were themselves generated by VADER, "evaluating VADER against these
labels" is measuring self-consistency, not independent accuracy — VADER
will trivially agree with its own prior output. The agreement score printed
below is reported for completeness but should not be read as a genuine
accuracy metric. For a real accuracy/F1 evaluation as the brief requests,
you would need independently human-labeled sentiment data, which doesn't
exist for this synthetic dataset.

For the brief-specified transformer-based sentiment models
(distilbert-base-uncased-finetuned-sst-2-english, cardiffnlp/twitter-roberta-
base-sentiment), see 03b_sentiment_analysis_huggingface.py — written to
spec but untested here (no huggingface.co access in this sandbox).

Usage:
    python 03_sentiment_analysis.py --input ../data/cleaned_queries.csv
"""

import argparse

import pandas as pd
from sklearn.metrics import accuracy_score, classification_report
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()


def get_sentiment(text: str) -> str:
    score = analyzer.polarity_scores(text)["compound"]
    if score <= -0.3:
        return "angry"
    elif score >= 0.3:
        return "happy"
    else:
        return "neutral"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="../data/cleaned_queries.csv")
    args = parser.parse_args()

    df = pd.read_csv(args.input)
    df["vader_sentiment"] = df["text"].apply(get_sentiment)

    agreement = accuracy_score(df["sentiment"], df["vader_sentiment"])
    print(f"Agreement with dataset's existing sentiment labels: {agreement:.1%}")
    print("(See module docstring: this measures self-consistency, not independent accuracy,")
    print(" since both were generated by the same VADER thresholds.)\n")
    print(classification_report(df["sentiment"], df["vader_sentiment"], zero_division=0))


if __name__ == "__main__":
    main()
